version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: xrechnung_postgresql
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data